create table if not exists public.management_tasks (
  id bigint generated by default as identity primary key,
  section_key text not null check (section_key in ('captacion', 'seguimiento', 'modulos', 'expansion', 'operacion')),
  title text not null,
  detail text,
  owner text,
  link_url text,
  sort_order integer not null default 0,
  is_done boolean not null default false,
  created_by uuid references auth.users (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists management_tasks_section_sort_idx
  on public.management_tasks (section_key, sort_order, created_at);

alter table public.management_tasks enable row level security;

drop policy if exists "Admins can read management tasks" on public.management_tasks;
create policy "Admins can read management tasks"
  on public.management_tasks
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.is_admin = true
    )
  );

drop policy if exists "Admins can insert management tasks" on public.management_tasks;
create policy "Admins can insert management tasks"
  on public.management_tasks
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.is_admin = true
    )
  );

drop policy if exists "Admins can update management tasks" on public.management_tasks;
create policy "Admins can update management tasks"
  on public.management_tasks
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.is_admin = true
    )
  )
  with check (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.is_admin = true
    )
  );

drop policy if exists "Admins can delete management tasks" on public.management_tasks;
create policy "Admins can delete management tasks"
  on public.management_tasks
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.profiles
      where profiles.id = auth.uid()
        and profiles.is_admin = true
    )
  );

do $$
begin
  alter publication supabase_realtime add table public.management_tasks;
exception
  when duplicate_object then null;
end
$$;

insert into public.management_tasks (section_key, title, owner, detail, link_url, sort_order, is_done)
select *
from (
  values
    ('captacion', 'Ordenar base de datos con inscritos + pagados', 'Vale / Valentina', null, 'https://docs.google.com/spreadsheets/d/1CckvGXAfemvd8AWGtUEewZkWnjofQYL0uNUhft9ZTe0/edit?gid=0#gid=0', 10, false),
    ('captacion', 'Enviar emails personalizados', 'Pablo / Lucia / Mauricio', null, 'https://docs.google.com/spreadsheets/d/1uwnpSX7iGTc7N5UcYVjIIVHYudL-ERsdCGSq-T2OJI0/edit', 20, false),
    ('captacion', 'Empujar Instagram', 'Equipo', null, null, 30, false),
    ('captacion', 'Activar LinkedIn', 'Todos', null, null, 40, false),
    ('captacion', 'Follow up con Pato Navia', 'Redes de cada uno', null, null, 50, false),
    ('captacion', 'Pensar en PTRPS', 'Redes de cada uno', null, null, 60, false),
    ('seguimiento', 'Hacer seguimiento a quienes ya pagaron', 'Clave', 'Usar la lista viva del dashboard y la planilla compartida para no perder trazabilidad.', 'https://docs.google.com/spreadsheets/d/1CckvGXAfemvd8AWGtUEewZkWnjofQYL0uNUhft9ZTe0/edit?gid=0#gid=0', 70, false),
    ('modulos', 'Editar archivos de módulos en Google Drive', 'Todos', null, 'https://drive.google.com/drive/folders/15PttPjVKjH1D3NkL8welw4kul-9iOouP', 80, false),
    ('expansion', 'Hablar con Tania Hutt sobre expansión a mineras', 'Mauricio / Pablo', null, null, 90, false),
    ('operacion', 'Dar login a quienes pagaron', null, 'Usar el panel de usuarios para activar acceso apenas se confirme el pago.', '#admin-section', 100, false),
    ('operacion', 'Empezar a subir contenido a la página', null, 'Slides, PDFs, videos y otros materiales del taller.', '#admin-section', 110, false)
) as seed(section_key, title, owner, detail, link_url, sort_order, is_done)
where not exists (
  select 1
  from public.management_tasks
);
