-- seguimiento_inscritos: tabla para tracking de inscritos al Taller Doble A
-- Leida desde el Google Sheet y actualizada por sync_inscritos.py
-- RLS: solo admins autenticados pueden leer/escribir (mismo patron que management_tasks)

create table if not exists public.seguimiento_inscritos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  correo text,
  telefono text,
  nivel text,
  estatus text,
  seguimiento_pablo boolean not null default false,
  grupo text not null check (grupo in ('pagado','esperanza','perdido')),
  prioridad_llamar boolean not null default false,
  actualizado_at timestamptz not null default now()
);

create unique index if not exists seguimiento_inscritos_correo_key
  on public.seguimiento_inscritos (lower(correo))
  where correo is not null and correo <> '';

create index if not exists seguimiento_inscritos_grupo_idx
  on public.seguimiento_inscritos (grupo, prioridad_llamar desc, seguimiento_pablo desc, nombre);

alter table public.seguimiento_inscritos enable row level security;

drop policy if exists "Admins can read seguimiento" on public.seguimiento_inscritos;
create policy "Admins can read seguimiento"
  on public.seguimiento_inscritos
  for select
  to authenticated
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.is_admin = true
    )
  );

drop policy if exists "Admins can insert seguimiento" on public.seguimiento_inscritos;
create policy "Admins can insert seguimiento"
  on public.seguimiento_inscritos
  for insert
  to authenticated
  with check (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.is_admin = true
    )
  );

drop policy if exists "Admins can update seguimiento" on public.seguimiento_inscritos;
create policy "Admins can update seguimiento"
  on public.seguimiento_inscritos
  for update
  to authenticated
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.is_admin = true
    )
  )
  with check (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.is_admin = true
    )
  );

drop policy if exists "Admins can delete seguimiento" on public.seguimiento_inscritos;
create policy "Admins can delete seguimiento"
  on public.seguimiento_inscritos
  for delete
  to authenticated
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.is_admin = true
    )
  );

-- SEED con los 44 inscritos actuales (Apr 17 2026)
-- Hacer re-run seguro via upsert por correo
insert into public.seguimiento_inscritos
  (nombre, correo, telefono, nivel, estatus, seguimiento_pablo, grupo, prioridad_llamar)
values
  ('Cristóbal Castro Baeza', 'cristobal.castro2@mail.udp.cl', null, 'Intermedio', 'Inscripción pagada', false, 'pagado', false),
  ('Susan Vidal', 'susan.vidal.ayala@gmail.com', '56948499323', null, 'Se envio información por whatsapp y no esta interesada en participar por tiempos y otros compromisos', false, 'perdido', false),
  ('Cynthia Gangas', 'gangas.cynthia@gmail.com', '992318520', null, 'Se envio mensaje con oferta personalizada. Por motivos de viaje no podrá ser participe en esta ocasion 10/04', false, 'esperanza', false),
  ('Dafne Cornejo', 'dafne.cornejo.oliva@gmail.com', '940166599', null, 'Se le envió mensaje con oferta personalizada. Por razones personales no podrá participar en esta ocasión 10/04', false, 'perdido', false),
  ('Juan Reyes', 'juig.reva@gmail.com', null, null, 'Información  enviada', false, 'esperanza', false),
  ('Yuliana Fuentes', 'yuliana.fuentes@ug.uchile.cl', '941002885', null, 'Información enviada. Se le hizo seguimiento el 1 de abril. el 06 de abril se le volvio a escribir sin respuesta (Hacer seguimiento)', true, 'esperanza', false),
  ('Thomas Campos', 'thomascamposb@gmail.com', '56988088713', null, 'No podrá participar', false, 'perdido', false),
  ('Francisca Acevedo', 'francisca.acevedo@uc.cl', '979878832', 'Intermedio', 'Inscripción pagada', false, 'pagado', false),
  ('Valeria Reyes', 'valeria.reyes.v@ug.uchile.cl', '956202259', null, 'No está interesada. Es muy caro para su presupuesto. Mensaje con oferta personalizada enviado. No esta interesada', false, 'perdido', false),
  ('Pedro Valenzuela', 'Pedro.valenzuelab@mail.udp.cl', '569 99055597', null, 'No está interesado. Pensaba que era gratis el taller. Mensaje con oferta personalizada enviado (Hacer seguimiento)', false, 'esperanza', false),
  ('Ricardo León', 'ricardoleonc76@gmail.com', '963622904', null, 'Se envio mensaje con oferta personalizada. Sin respuesta 10/04. Se volvio a escribir 14/04 (Hacer seguimiento)', true, 'esperanza', false),
  ('Diego Torres', 'diegobastianvt2@gmail.com', '996377517', null, 'No podrá participar por presupuestos y tiempos (carga académica)', false, 'perdido', false),
  ('Luz Escobar', 'luz.escobar.h@ug.uchile.cl', '56931004413', null, 'Se escapa de su presupuesto el valor del taller', false, 'esperanza', false),
  ('Martin Alister', 'Martin.alister20@gmail.com', '56944132551', null, 'Pidió más información, la cual fue enviada, por carga académica no puede participar', false, 'perdido', false),
  ('Antonia Baeza', 'antonia.baeza@ug.uchile.cl', '56964893752', null, 'Por presupuesto no podrá participar. Mensaje con oferta personalizada enviado. No esta interesada', false, 'perdido', false),
  ('Fernanda Palma', 'fernanda.palma@ug.uchile.cl', '56984725752', null, 'Seguimiento (10/04) sin respuesta. Se volvio a ahcer seguimiento 14/04 (hacer seguimiento)', true, 'esperanza', false),
  ('Vicente Villalobos', 'vicentevillalobos522@gmail.com', null, null, 'Información enviada. Por presupuesto no peude participar, se le envio mensaje con oferta personalizada sin respuesta 14/04', false, 'esperanza', false),
  ('Sofia Paz Tapia', 'sofia.paz@ug.uchile.cl', null, null, 'Por tiempos no podrá participar (inicia diplomado)', false, 'perdido', false),
  ('Nicolás Gajardo Ortíz', 'nicolas.gajardo.o@ug.uchile.cl', null, null, 'Pidió más infromación sobre la inscripción, se le envio la información sin obtener respuesta, se le hizo seguimiento 10/04. Se envio mensaje con oferta personaliza 14/04 a la espera de respuesta', false, 'esperanza', false),
  ('Melanie Ballesteros Palma', 'melanieballesterospalma@gmail.com', null, 'básico', 'Inscripción pagada', false, 'pagado', false),
  ('José Jiménez Guerrero', 'jjimenezg185@gmail.com', null, null, 'Información enviada. Por presupuesto no puede participar, se le oreció ofeerta personalizada, no esta interesado.', false, 'perdido', false),
  ('Felipe Rodriguez', 'ferodriguezp19@gmail.com', null, null, 'Información enviada. sin respuesta, se le hizo seguimiento en 3 ocasiones, sin respuesta', false, 'esperanza', false),
  ('Luciano Alvarez', 'luciano.alvarez@ug.uchile.cl', null, null, 'Por costos no participará. Se le envio mensaje con oferta personalizada sin respuest 14/04', false, 'perdido', false),
  ('Jesus diaz', 'jesus.diaz.m@ug.uchile.cl', null, null, 'Información enviada. Por costos no puede participar. Se le envio mensaje con oferta personalizada sin respuesta 14/04', false, 'perdido', false),
  ('Ana Carolina Riquelme', 'ana.riquelme_l@mail.udp.cl', null, null, 'Información enviada. Se hizo seguimineto 07/04. Se volvió a enviar mensaje con oferta personalizada 14/04', false, 'esperanza', false),
  ('Alejandro Reyes', 'areyeso@ug.uchile.cl', null, null, 'Información enviada', false, 'esperanza', false),
  ('Felipe Silva', 'fsilvag06@gmail.com', '989397060', null, 'Información enviada. Pensó que era sin costo el taller. Se le envio mensaje con oferta personalizada, no esta interesado', false, 'perdido', false),
  ('Camila Cuevas', 'camilacuevas.g11@gmail.com', '56992310527', null, 'Información enviada, esta interesada pero tiene otros compromisos y gastos, se le ofrecio descuento. (Hacer seguimiento)', true, 'esperanza', false),
  ('Carola Zurob', 'czurob@uc.cl', '56992507401', null, null, false, 'esperanza', false),
  ('Macarena Zuazua', 'macarena.zuazua@ekhos.cl', '56973971789', 'Intermedio', 'Inscripción pagada', true, 'pagado', false),
  ('Violeta Tapia', 'violeta.tapia.venegas@gmail.com', '56940493040', null, 'Mensaje enviado el 10/04, por presupuesto le complica, pero se le ofrecio oferta personalizada y nos avisará cualquier cosa', true, 'esperanza', false),
  ('Rafaella Rivera', 'rrafaellaq@gmail.com', null, null, 'Pidio más informacion. Esta de intervcambio fuera del país, se le envio mensaje con oferta personalizada a la espera de respuesta', true, 'esperanza', false),
  ('Emilia Wells', 'emilia.wells@ug.uchile.cl', '956094232', null, 'Pidio más informacion. se le envio mensaje con oferta personalizada. No podrá participar', true, 'perdido', false),
  ('Benjamín Tardy D.', 'benjamin.tardy@ug.uchile.cl', null, null, 'Información enviada', true, 'esperanza', false),
  ('Monserrat masso', 'Monserratmasso@gmail.com', '+56944531225', null, 'Información enviada (llamar)', true, 'esperanza', true),
  ('Isidora Barros', 'isidora.barros@mail.udp.cl', '966729942', null, 'Información enviada. Mensaje con oferta personalizada enviado 13/04 a la espera de respuesta (llamar)', true, 'esperanza', true),
  ('Patricio Alarcón', 'patricio.alarcon@mail.udp.cl', '+56949427904', 'Avanzado', 'Inscripción pagada', true, 'pagado', false),
  ('Cristian Carreño', 'cristian.carreno@nyu.edu', null, null, 'Inscripción pagada', true, 'pagado', false),
  ('Gabriel Henríquez', 'Gabriel.henriquezrojas@gmail.com', '982987379', null, 'No podrá por tiempos y costos del taller. Se envio mensaje con oferta personalizada. No esta intereesado 10/04', false, 'perdido', false),
  ('Maximiliano Saavedra Guerrero', 'm.saavedra.1@ug.uchile.cl', '945654421', null, 'Por tiempos no podrá participar', false, 'perdido', false),
  ('Cristóbal Unda Labbé', 'cristobal.unda@ug.uchile.cl', '999984034', null, 'No habia revisado el correo. Revisara la información al finalizar la semana confirmara si podrá participar. respondió que desistio de participarr', false, 'perdido', false),
  ('Diego Fernández', 'diegomora.adrian@gmail.com', '56 9 5592 2497', null, 'No habia revisado el correo. Revisara la información. Dijo que no estaba interesado en estos momentos 06/04', false, 'perdido', false),
  ('Viviana Sanchez', 'v.sanchezpizarro@gmail.com', '56997378549', null, 'No contesta. Whatsapp enviado a la espera de respuesta 06/04. Otro mensaje con oferta personalizada enviado el 08/04 sin respuesta', false, 'esperanza', false),
  ('Noeh Mella', 'cristobal.mella.s@ug.uchile.cl', '56995149355', null, 'Mail enviado 16/04', false, 'esperanza', false)
on conflict (lower(correo)) where correo is not null and correo <> ''
do update set
  nombre = excluded.nombre,
  telefono = excluded.telefono,
  nivel = excluded.nivel,
  estatus = excluded.estatus,
  seguimiento_pablo = excluded.seguimiento_pablo,
  grupo = excluded.grupo,
  prioridad_llamar = excluded.prioridad_llamar,
  actualizado_at = now();
